### PR TITLE
Fix: gradle plugin

### PR DESCRIPTION
**Pull request by vnnv**
Fix: > Plugin with id 'ebean' not found.

because ebean.properties was renamed to io.ebean.properties ebean plugin can not be started using apply plugin: ebean

I alse updated README.md - using latest eben versions. 
Please review and merge.

### CODE REVIEW

**Comment by rbygrave** [comment]
It looks good except for that rename of the io.ebean.properties file ... I think that file name needs to match the plugin id which changed from "ebean" to "io.ebean" 

... but yes I'll merge it in shortly and check.

Cheers, Rob.

**Comment by vnnv** [comment]
if the file is named io.ebean.properties gradle can not find the plugin using apply plugin: 'ebean'. Maybe one must use apply plugin: 'io.ebean'  than. I did not check that. But if we want to use 'ebean' as plugin name the file must be ebean.properties

**Comment by rbygrave** [comment]
Yes, we need to use:

apply plugin: 'io.ebean'


We had to change the name to 'io.ebean' to deploy to the Gradle plugins
repo. That is how the plugin is deployed now to both to the gradle repo and
maven central.
So note that if we are not using 'io.ebean' ... we are not using the latest
released plugin.

**Comment by rbygrave** [comment]
Also, docs are at: http://ebean-orm.github.io/docs/tooling/gradle

... so we need to review those.

**Comment by vnnv** [comment]
In that case maybe only README should be merged along with changes to use io.ebean

**Comment by rbygrave** [comment]
Updated the README - should be all good now, closing.

**Pull request closed without merging**
